name: Java CI/CD Pipeline

# Definir el evento que activa el pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Etapa de Construcción y Pruebas
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Checkout del código
    - name: Checkout code
      uses: actions/checkout@v3

    # Paso 2: Configurar Java (usamos OpenJDK 8)
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        
    # Paso 3: Instalar dependencias y construir el proyecto con Maven
    - name: Build with Maven
      run: mvn clean install

    # Paso 4: Ejecutar pruebas unitarias
    - name: Run tests
      run: mvn test

  # Etapa de Despliegue (simulado)
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Simulate deployment
        run: |
          echo "Simulando despliegue..."
          mkdir deploy
          cp -r $(ls | grep -v deploy) deploy/
          echo "Aplicación desplegada en carpeta deploy"
